export const siteConfig = {
  name: "Events by Momin",
  shortName: "Events by Momin",
  tagline: "South Punjab's Most Trusted Name in Event Decor & Management",
  description:
    "Events by Momin is South Punjab's leading event management and decor company, serving Rahim Yar Khan (RYK), Sadiqabad (SDK), Khanpur, Goth Machi, Liaqatpur and all surrounding areas. We specialize in wedding decor, barat and walima stages, mehndi and dholki setups, birthday parties, gala nights, mango parties, office and corporate events, engagements, baby showers and every celebration in between.",
  url: "https://eventsbymomin.com",
  email: "eventbymomin@gmail.com",
  phoneDisplay: "+92 309 4439441",
  phoneRaw: "+923094439441",
  whatsappLink: "https://wa.me/923094439441",
  instagram: "https://instagram.com/events_by_momin_official",
  instagramHandle: "@events_by_momin_official",
  facebook: "https://facebook.com/eventsbymomin",
  facebookName: "Events by Momin",
  linkedin: "https://www.linkedin.com/in/events-by-momin-81406b434/",
  pinterest: "https://www.pinterest.com/eventsbymomin/",
  tiktok: "https://www.tiktok.com/@events_by_momin_official",
  addressRegion: "Punjab",
  addressCountry: "PK",
  primaryCity: "Rahim Yar Khan",
  streetAddress: "Darhi Sanghi, Near Dominos",
  fullAddress: "Darhi Sanghi, Near Dominos, Rahim Yar Khan, Punjab, Pakistan",
  mapEmbedSrc:
    "https://maps.google.com/maps?q=Darhi%20Sanghi%2C%20Near%20Dominos%2C%20Rahim%20Yar%20Khan%2C%20Punjab%2C%20Pakistan&t=&z=15&ie=UTF8&iwloc=&output=embed",
  serviceAreas: [
    "Rahim Yar Khan (RYK)",
    "Sadiqabad (SDK)",
    "Khanpur",
    "Goth Machi",
    "Liaqatpur",
    "Ahmadpur East",
    "Sadiq Colony",
    "All of South Punjab",
  ],
  keywords: [
    // Brand
    "Events by Momin",
    "Events by Momin Rahim Yar Khan",
    "eventsbymomin",
    "events_by_momin",
    "momin events",
    "momin_events",
    // Core / generic event management
    "event management company",
    "event management company Rahim Yar Khan",
    "event planner near me",
    "event planner RYK",
    "best event planner in Rahim Yar Khan",
    "best event planner in South Punjab",
    "event organizer near me",
    "event organizer in Rahim Yar Khan",
    "event management services South Punjab",
    "professional event planner Pakistan",
    "party planning services",
    "party planner near me",
    "party planner in Rahim Yar Khan",
    "event decorator near me",
    "decoration company near me",
    "decoration company in RYK",
    "top rated event management company",
    "event management company Sadiqabad",
    "event management company Khanpur",
    "event management company Liaqatpur",
    "event management company Goth Machi",
    "best event planner in Sadiqabad",
    "best events planner in Sadiqabad",
    "events planner Sadiqabad",
    "event planner Sadiqabad",
    "event organizer Sadiqabad",
    "party planner Sadiqabad",
    "decoration company Sadiqabad",
    "best event planner in Goth Machi",
    "events planner Goth Machi",
    "event planner Goth Machi",
    "event organizer Goth Machi",
    "wedding planner Goth Machi",
    "decoration company Goth Machi",
    // Weddings
    "wedding planner Rahim Yar Khan",
    "wedding decor Rahim Yar Khan",
    "wedding decor Sadiqabad",
    "wedding decorator Khanpur",
    "wedding decor Goth Machi",
    "wedding planner Liaqatpur",
    "wedding stage decoration",
    "wedding stage design",
    "wedding flower decoration",
    "bridal stage decor",
    "nikah stage decoration",
    "wedding backdrop design",
    "luxury wedding decor Pakistan",
    "affordable wedding decor Pakistan",
    "best wedding decorator in South Punjab",
    "wedding decoration packages",
    "wedding decoration prices",
    // Barat & Walima
    "barat decoration RYK",
    "barat stage decor",
    "barat stage design",
    "walima decoration",
    "walima stage RYK",
    "walima reception decor",
    "valima decoration",
    "groom stage decoration",
    // Mehndi & Dholki
    "mehndi decoration RYK",
    "mehndi stage setup",
    "mehndi decor near me",
    "mehndi decoration ideas",
    "dholki decoration",
    "dholki setup Pakistan",
    "mehndi function decoration",
    "mehndi backdrop design",
    "henna night decoration",
    // Engagement, anniversary, bridal
    "engagement decoration",
    "ring ceremony decoration",
    "engagement stage RYK",
    "anniversary party planner",
    "anniversary decoration",
    "bridal shower decoration",
    // Birthdays
    "birthday party decoration Khanpur",
    "birthday party planner RYK",
    "birthday party planner Sadiqabad",
    "kids birthday party planner",
    "birthday party decoration near me",
    "birthday balloon decoration",
    "birthday party packages",
    "1st birthday party decoration",
    "theme birthday party decoration",
    // Gala nights & corporate
    "gala night decor",
    "gala night event planner",
    "office party planner RYK",
    "corporate event management South Punjab",
    "corporate event planner Pakistan",
    "annual dinner event management",
    "product launch event management",
    "conference event planning",
    "seminar event planning",
    "exhibition stall decoration",
    "trade show event management",
    // Mango party & theme parties
    "mango party theme",
    "mango party decoration",
    "summer theme party decoration",
    "theme party decoration",
    // Family & seasonal events
    "baby shower decoration RYK",
    "baby shower planner",
    "welcome baby party decoration",
    "aqeeqa decoration",
    "get together party planner",
    "family function decoration",
    "farewell party decoration",
    "welcome party decoration",
    "graduation party decoration",
    "eid party decoration",
    "new year party decoration",
    // Decor & service types
    "balloon decoration RYK",
    "balloon arch decoration",
    "flower decoration wedding",
    "artificial flower decoration",
    "fresh flower decoration wedding",
    "LED stage decoration",
    "lighting decoration for events",
    "tent and marquee decoration",
    "stage lighting services",
    "backdrop and photo booth decoration",
    "flower wall decoration",
    "catering services Rahim Yar Khan",
    "DJ services for wedding Pakistan",
    "sound system rental for events",
    "event decoration packages",
    "event management company South Punjab",
    // Popular search phrases
    "wedding decor near me",
    "best wedding planner in RYK",
    "barat stage decoration",
    "walima stage setup",
    "dholki party planner",
    "birthday party decoration",
    "mango party theme decoration",
    "office party planner",
    "corporate event management",
    "baby shower decoration",
    "backdrop and photo booth design",
    "luxury event decor",
    "event planner in Khanpur",
    "wedding decorator in Liaqatpur",
    "event planner in Goth Machi",
    "wedding decorator in Goth Machi",
    "get together event planner",
    "catering services in RYK",
    // "Best in RYK / Rahim Yar Khan" — high-intent ranking keywords
    "best event planner in RYK",
    "best event planner in Rahim Yar Khan",
    "best event planner RYK",
    "best event decor in RYK",
    "best event decoration in Rahim Yar Khan",
    "best event decoration RYK",
    "best event services in RYK",
    "best event services Rahim Yar Khan",
    "best event management in Rahim Yar Khan",
    "best event management RYK",
    "best event company in RYK",
    "best event company Rahim Yar Khan",
    "best wedding planner in RYK",
    "best wedding planner in Rahim Yar Khan",
    "best wedding decorator in RYK",
    "best wedding decorator Rahim Yar Khan",
    "best event decorator in RYK",
    "best event decorator Rahim Yar Khan",
    "best decoration company in RYK",
    "best decoration company Rahim Yar Khan",
    "best mehndi decorator in RYK",
    "best mehndi decoration Rahim Yar Khan",
    "best barat stage decorator RYK",
    "best walima decoration RYK",
    "best birthday party planner RYK",
    "best gala night planner RYK",
    "best corporate event planner RYK",
    "best catering service in RYK",
    "best catering service Rahim Yar Khan",
    "best tent decoration RYK",
    "best shamiana decoration Rahim Yar Khan",
    "best party planner in RYK",
    "best party planner Rahim Yar Khan",
    "top event planner RYK",
    "top event management company RYK",
    "top rated event planner Rahim Yar Khan",
    "top rated decorator RYK",
    "number 1 event planner RYK",
    "No 1 event planner Rahim Yar Khan",
    "number one event planner South Punjab",
    "professional event planner RYK",
    "trusted event planner RYK",
    "experienced event planner RYK",
    "leading event management company RYK",
    "famous event planner Rahim Yar Khan",
    "most popular event planner RYK",
    "most searched event planner RYK",
    "top decoration company South Punjab",
    "best decoration company South Punjab",
    "best event organizer RYK",
    "best event organizer Rahim Yar Khan",
    // MUN & school/college events
    "MUN event management Rahim Yar Khan",
    "RYK MUN",
    "Model United Nations event management",
    "MUN stage decoration Pakistan",
    "school event management RYK",
    "college event management South Punjab",
    "conference stage decoration Rahim Yar Khan",
    "event management company for MUN Pakistan",
  ],
};
